"use strict";

const STORAGE_KEY = "tp-vertriebscockpit-demo-v1";
const owners = [];

function refreshOwners() {
  const names = new Set();

  (data.employees || [])
    .filter((employee) => employee.active !== false)
    .forEach((employee) => {
      const name = String(employee.displayName || "").trim();
      if (name) names.add(name);
    });

  ["customers", "activities", "appointments", "followups"].forEach((collectionName) => {
    (data[collectionName] || []).forEach((record) => {
      const name = String(record.owner || "").trim();
      if (name) names.add(name);
    });
  });

  owners.splice(0, owners.length, ...[...names].sort((a, b) => a.localeCompare(b, "de")));
}
const pipelineStages = [
  "01 Lead",
  "02 Kontaktversuch",
  "03 Kontakt hergestellt",
  "04 Termin vereinbart",
  "05 Bedarf qualifiziert",
  "06 Angebot",
  "07 Verhandlung",
  "08 Gewonnen",
  "09 Verloren",
];
const today = new Date();
const iso = (d) => new Date(d).toISOString().slice(0, 10);
const addDays = (n) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return iso(d);
};

const seedData = {
  customers: [
    {
      id: "K-1001",
      type: "Bestandskunde",
      name: "Meyer Haustechnik GmbH",
      street: "Industriestraße 12",
      zip: "21614",
      city: "Buxtehude",
      contact: "Thomas Meyer",
      phone: "04161 555210",
      mobile: "0171 2345678",
      email: "t.meyer@beispiel.de",
      owner: "Anna Becker",
      pipeline: "08 Gewonnen",
      potential: "A – sehr hoch",
      trades: ["Sanitär", "Heizung"],
      lastContact: addDays(-18),
      nextAppointment: addDays(2),
      note: "Interesse an neuer Produktlinie und gemeinsamer Schulung.",
    },
    {
      id: "K-1002",
      type: "Interessent",
      name: "Dach & Solar Nord GmbH",
      street: "Am Markt 7",
      zip: "21680",
      city: "Stade",
      contact: "Laura Hansen",
      phone: "04141 661122",
      mobile: "",
      email: "hansen@beispiel.de",
      owner: "Michael Krüger",
      pipeline: "05 Bedarf qualifiziert",
      potential: "B – hoch",
      trades: ["Dach", "Elektro"],
      lastContact: addDays(-7),
      nextAppointment: addDays(5),
      note: "Bedarf für PV-Unterkonstruktion und Elektrokomponenten.",
    },
    {
      id: "K-1003",
      type: "Kaltakquise",
      name: "Elbe Ausbau KG",
      street: "Hafenstraße 28",
      zip: "21079",
      city: "Hamburg",
      contact: "Jan Richter",
      phone: "040 775533",
      mobile: "",
      email: "",
      owner: "Svenja Peters",
      pipeline: "02 Kontaktversuch",
      potential: "B – hoch",
      trades: ["Trockenbau", "Boden"],
      lastContact: addDays(-4),
      nextAppointment: "",
      note: "Beim ersten Versuch nicht erreicht.",
    },
    {
      id: "K-1004",
      type: "Bestandskunde",
      name: "Schulz Gebäudetechnik",
      street: "Bahnhofstraße 44",
      zip: "27404",
      city: "Zeven",
      contact: "Peter Schulz",
      phone: "04281 99880",
      mobile: "",
      email: "info@beispiel.de",
      owner: "Anna Becker",
      pipeline: "06 Angebot",
      potential: "A – sehr hoch",
      trades: ["Heizung", "Klima", "Lüftung"],
      lastContact: addDays(-202),
      nextAppointment: "",
      note: "Offenes Angebot nachfassen.",
    },
    {
      id: "K-1005",
      type: "Interessent",
      name: "Nordlicht Elektrotechnik GmbH",
      street: "Feldstraße 5",
      zip: "21244",
      city: "Buchholz",
      contact: "Miriam Lange",
      phone: "04181 400550",
      mobile: "",
      email: "lange@beispiel.de",
      owner: "Michael Krüger",
      pipeline: "04 Termin vereinbart",
      potential: "C – mittel",
      trades: ["Elektro"],
      lastContact: addDays(-12),
      nextAppointment: addDays(1),
      note: "Ersttermin vor Ort.",
    },
    {
      id: "K-1006",
      type: "Kaltakquise",
      name: "Baukonzept Altes Land",
      street: "Obstmarschenweg 9",
      zip: "21635",
      city: "Jork",
      contact: "Kai Martens",
      phone: "04162 889900",
      mobile: "",
      email: "",
      owner: "Svenja Peters",
      pipeline: "01 Lead",
      potential: "C – mittel",
      trades: ["Dach", "Fassade"],
      lastContact: "",
      nextAppointment: "",
      note: "Neuer Datensatz aus Akquiseliste.",
    },
  ],
  activities: [
    {
      id: "A-1",
      date: addDays(-1),
      customerId: "K-1002",
      owner: "Michael Krüger",
      type: "Telefon",
      goal: "Bedarfsanalyse",
      result: "Bedarf erkannt",
      next: "Termin vorbereiten",
      due: addDays(4),
      note: "Entscheiderin nimmt am Termin teil.",
    },
    {
      id: "A-2",
      date: addDays(-2),
      customerId: "K-1001",
      owner: "Anna Becker",
      type: "E-Mail",
      goal: "Bestandskundenpflege",
      result: "Information gesendet",
      next: "Rückmeldung abwarten",
      due: addDays(7),
      note: "Unterlagen zur Schulung versendet.",
    },
    {
      id: "A-3",
      date: addDays(-4),
      customerId: "K-1003",
      owner: "Svenja Peters",
      type: "Kaltakquise Telefon",
      goal: "Neukundengewinnung",
      result: "Nicht erreicht",
      next: "Erneut anrufen",
      due: addDays(1),
      note: "Zentrale verwies auf Vormittag.",
    },
    {
      id: "A-4",
      date: addDays(-6),
      customerId: "K-1005",
      owner: "Michael Krüger",
      type: "Telefon",
      goal: "Neukundengewinnung",
      result: "Termin vereinbart",
      next: "Vor-Ort-Termin",
      due: addDays(1),
      note: "Schwerpunkt Elektrokomponenten.",
    },
    {
      id: "A-5",
      date: addDays(-8),
      customerId: "K-1004",
      owner: "Anna Becker",
      type: "Angebot",
      goal: "Angebot nachfassen",
      result: "Angebot erstellt",
      next: "Angebot telefonisch nachfassen",
      due: addDays(-3),
      note: "Angebot übermittelt.",
    },
    {
      id: "A-6",
      date: addDays(-12),
      customerId: "K-1002",
      owner: "Michael Krüger",
      type: "Vor-Ort-Besuch",
      goal: "Produktvorstellung",
      result: "Bedarf erkannt",
      next: "Folgetermin",
      due: addDays(5),
      note: "Gutes Gespräch, konkretes Projekt vorhanden.",
    },
  ],
  appointments: [
    {
      id: "T-1",
      date: addDays(1),
      time: "09:30",
      customerId: "K-1005",
      owner: "Michael Krüger",
      subject: "Ersttermin / Bedarfsermittlung",
      note: "Produktmuster mitnehmen",
    },
    {
      id: "T-2",
      date: addDays(2),
      time: "11:00",
      customerId: "K-1001",
      owner: "Anna Becker",
      subject: "Jahresgespräch",
      note: "Umsatzentwicklung vorbereiten",
    },
    {
      id: "T-3",
      date: addDays(5),
      time: "14:00",
      customerId: "K-1002",
      owner: "Michael Krüger",
      subject: "Projektbesprechung",
      note: "PV und Elektro",
    },
    {
      id: "T-4",
      date: addDays(7),
      time: "08:30",
      customerId: "K-1003",
      owner: "Svenja Peters",
      subject: "Akquisebesuch",
      note: "Termin noch bestätigen",
    },
  ],
  followups: [
    {
      id: "W-1",
      customerId: "K-1004",
      owner: "Anna Becker",
      due: addDays(-3),
      priority: "Hoch",
      task: "Offenes Angebot telefonisch nachfassen",
      status: "Offen",
    },
    {
      id: "W-2",
      customerId: "K-1003",
      owner: "Svenja Peters",
      due: addDays(1),
      priority: "Mittel",
      task: "Zweiten telefonischen Kontaktversuch starten",
      status: "Offen",
    },
    {
      id: "W-3",
      customerId: "K-1002",
      owner: "Michael Krüger",
      due: addDays(4),
      priority: "Hoch",
      task: "Unterlagen für Projekttermin vorbereiten",
      status: "In Bearbeitung",
    },
    {
      id: "W-4",
      customerId: "K-1001",
      owner: "Anna Becker",
      due: addDays(7),
      priority: "Niedrig",
      task: "Termin für Produktschulung abstimmen",
      status: "Offen",
    },
    {
      id: "W-5",
      customerId: "K-1005",
      owner: "Michael Krüger",
      due: addDays(-1),
      priority: "Mittel",
      task: "Besuchsbericht ergänzen",
      status: "Erledigt",
    },
  ],
};
